# Generated by Django 5.0.6 on 2024-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPhoneNum', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=100)),
                ('companyRegisteredId', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=20)),
                ('tan', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('coi', models.FileField(blank=True, null=True, upload_to='company/coi/')),
                ('address', models.TextField()),
                ('leavePolicy', models.FileField(blank=True, null=True, upload_to='company/leave_policies/')),
                ('pfPolicy', models.FileField(blank=True, null=True, upload_to='company/pf_policies/')),
                ('labourLawLicence', models.FileField(blank=True, null=True, upload_to='company/labour_law_licences/')),
            ],
        ),
    ]
