# Generated by Django 5.0.6 on 2024-09-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
