# Generated by Django 5.0.6 on 2024-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_delete_companydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPhoneNum', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=100)),
                ('companyRegisteredId', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=20)),
                ('tan', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('coi', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('leavePolicy', models.CharField(max_length=256)),
                ('pfPolicy', models.CharField(max_length=256)),
                ('labourLawLicence', models.CharField(max_length=256)),
            ],
        ),
    ]
