# Generated by Django 5.0.6 on 2024-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='coi',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='labourLawLicence',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='leavePolicy',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pfPolicy',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
