# Generated by Django 5.0.6 on 2024-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companydetails_coi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='labourLawLicence',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='leavePolicy',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pfPolicy',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
