# Generated by Django 5.0.6 on 2024-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companydetails_labourlawlicence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='coi',
            field=models.ImageField(blank=True, null=True, upload_to='coi/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='labourLawLicence',
            field=models.FileField(blank=True, null=True, upload_to='labour_law_policies/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='leavePolicy',
            field=models.FileField(blank=True, null=True, upload_to='leave_policies/'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pfPolicy',
            field=models.FileField(blank=True, null=True, upload_to='pf_policies/'),
        ),
    ]
