# Generated by Django 5.0.6 on 2024-09-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_employeecompensation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeCompensation',
        ),
    ]
