# Generated by Django 5.0.6 on 2024-10-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_delete_employeecompensation'),
        ('users', '0002_rename_userid_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.login'),
        ),
    ]
