# Generated by Django 5.0.6 on 2024-10-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companydetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_company_details_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='is_payroll_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
