# Generated by Django 5.0.6 on 2024-10-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companydetails_is_company_details_completed_and_more'),
        ('users', '0006_login_is_company_setup_complete_login_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='is_company_details_completed',
            new_name='employeeSetupDone',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='is_payroll_setup_completed',
            new_name='isCompanyDetailsCompleted',
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='labourLawLicence',
            new_name='labourLawLicense',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='user',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='users.login'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='payrollDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='adminName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='companyName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='companyRegisteredId',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='tan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
