# Generated by Django 5.0.6 on 2024-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_is_company_details_completed_companydetails_employeesetupdone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='companyRegisteredId',
            field=models.CharField(max_length=255),
        ),
    ]
