# Generated by Django 5.0.6 on 2024-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_companydetails_companyregisteredid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='labourLawLicense',
            new_name='labourLawLicence',
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='companyRegisteredId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
