# Generated by Django 5.0.6 on 2024-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_labourlawlicense_companydetails_labourlawlicence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='admin',
            new_name='user',
        ),
    ]
