# Generated by Django 5.0.6 on 2024-10-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rename_admin_companydetails_user'),
        ('users', '0007_remove_login_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.login'),
        ),
    ]
