# Generated by Django 5.0.6 on 2024-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('tsId', models.AutoField(primary_key=True, serialize=False)),
                ('empId', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=20)),
                ('no_of_days', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('lop_days', models.IntegerField()),
            ],
        ),
    ]
