# Generated by Django 5.0.6 on 2024-10-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companydetails_user'),
        ('employee', '0011_empworkdetails_company_and_more'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companydetails'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='empId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails', to_field='empId'),
        ),
    ]
