# Generated by Django 5.0.6 on 2024-10-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timesheet_company_alter_timesheet_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='OT',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
