# Generated by Django 5.0.6 on 2024-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='OT',
            field=models.IntegerField(default=0),
        ),
    ]
