# Generated by Django 5.0.6 on 2024-10-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companydetails_user'),
        ('employee', '0013_empsalarydetails_dapayamt_empsalarydetails_pf_type_and_more'),
        ('timesheet', '0004_alter_timesheet_ot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCalculation',
            fields=[
                ('tsId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=20)),
                ('no_of_days', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('lop_days', models.IntegerField()),
                ('OT', models.IntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ot_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ee_pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductibles_loans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companydetails')),
                ('empId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails', to_field='empId')),
            ],
        ),
    ]
