# Generated by Django 5.0.6 on 2024-10-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_paycalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='deductions',
            field=models.IntegerField(default=0),
        ),
    ]
