# Generated by Django 5.0.6 on 2024-11-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_timesheet_allowance_timesheet_deductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycalculation',
            old_name='deductibles_loans',
            new_name='deductiblesLoans',
        ),
        migrations.RenameField(
            model_name='paycalculation',
            old_name='ee_pf',
            new_name='eePF',
        ),
        migrations.RenameField(
            model_name='paycalculation',
            old_name='gross_pay',
            new_name='grossPay',
        ),
        migrations.RenameField(
            model_name='paycalculation',
            old_name='no_of_days',
            new_name='noOfDays',
        ),
        migrations.RenameField(
            model_name='paycalculation',
            old_name='ot_pay',
            new_name='otPay',
        ),
        migrations.RenameField(
            model_name='paycalculation',
            old_name='total_pay',
            new_name='totalPay',
        ),
        migrations.AddField(
            model_name='paycalculation',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paycalculation',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
