# Generated by Django 5.0.6 on 2024-11-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_rename_deductibles_loans_paycalculation_deductiblesloans_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycalculation',
            old_name='noOfDays',
            new_name='no_of_days',
        ),
    ]
