# Generated by Django 5.0.6 on 2024-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_rename_noofdays_paycalculation_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='OT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='lop_days',
            field=models.FloatField(),
        ),
    ]
