# Generated by Django 5.0.6 on 2024-11-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_alter_timesheet_ot_alter_timesheet_lop_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycalculation',
            name='OT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paycalculation',
            name='attendance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paycalculation',
            name='lop_days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='attendance',
            field=models.FloatField(),
        ),
    ]
