# Generated by Django 5.0.6 on 2024-09-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='userId',
            new_name='id',
        ),
    ]
