# Generated by Django 5.0.6 on 2024-10-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_login_last_login_alter_login_email_alter_login_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='login',
            name='userName',
            field=models.CharField(max_length=150),
        ),
    ]
