# Generated by Django 5.0.6 on 2024-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_login_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_payroll_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
