# Generated by Django 5.0.6 on 2024-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInsuranceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fathersName', models.CharField(max_length=100)),
                ('fathersDOB', models.DateField()),
                ('mothersName', models.CharField(max_length=100)),
                ('mothersDOB', models.DateField()),
                ('spouseName', models.CharField(blank=True, max_length=100, null=True)),
                ('spouseDOB', models.DateField(blank=True, null=True)),
                ('child1', models.CharField(blank=True, max_length=100, null=True)),
                ('child1DOB', models.DateField(blank=True, null=True)),
                ('child2', models.CharField(blank=True, max_length=100, null=True)),
                ('child2DOB', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpPersonalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personalEmailId', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('educationalQualification', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('marriageDate', models.DateField(blank=True, null=True)),
                ('currentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('generalContact', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('relationshipName', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('shirtSize', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmpSocialSecurityDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('panNumber', models.CharField(max_length=20)),
                ('uanNumber', models.CharField(max_length=20)),
                ('aadharNumber', models.CharField(max_length=20)),
                ('bankName', models.CharField(max_length=100)),
                ('ifscCode', models.CharField(max_length=20)),
                ('bankAccountNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpWorkDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empId', models.CharField(max_length=100)),
                ('employmentStatus', models.CharField(max_length=100)),
                ('companyEmailId', models.EmailField(max_length=254)),
                ('dateOfJoining', models.DateField()),
                ('dateOfRelieving', models.DateField(blank=True, null=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('roleType', models.CharField(max_length=100)),
                ('currentRole', models.CharField(max_length=100)),
                ('reportingManager', models.CharField(max_length=100)),
                ('reasonForLeaving', models.TextField(blank=True, null=True)),
                ('monthYearOfTermination', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExpInThisCompany', models.IntegerField(blank=True, null=True)),
                ('totalExperience', models.IntegerField(blank=True, null=True)),
                ('totalExpBeforeJoining', models.IntegerField(blank=True, null=True)),
                ('previousDateOfJoining', models.DateField(blank=True, null=True)),
                ('previousEmployer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
