# Generated by Django 5.0.6 on 2024-09-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkdetails',
            name='totalExpBeforeJoining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empworkdetails',
            name='totalExpInThisCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empworkdetails',
            name='totalExperience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
