# Generated by Django 5.0.6 on 2024-09-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_empworkdetails_totalexpbeforejoining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsocialsecuritydetails',
            old_name='aadharNumber',
            new_name='aadharNum',
        ),
        migrations.RenameField(
            model_name='empsocialsecuritydetails',
            old_name='panNumber',
            new_name='panNum',
        ),
        migrations.RenameField(
            model_name='empsocialsecuritydetails',
            old_name='uanNumber',
            new_name='uanNum',
        ),
    ]
