# Generated by Django 5.0.6 on 2024-09-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_aadharnumber_empsocialsecuritydetails_aadharnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonaldetails',
            name='shirtSize',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
