# Generated by Django 5.0.6 on 2024-09-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_emppersonaldetails_shirtsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinsurancedetails',
            name='fathersDOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empinsurancedetails',
            name='fathersName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empinsurancedetails',
            name='mothersDOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empinsurancedetails',
            name='mothersName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
