# Generated by Django 5.0.6 on 2024-09-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_empinsurancedetails_fathersdob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empinsurancedetails',
            old_name='id',
            new_name='isdId',
        ),
        migrations.RenameField(
            model_name='emppersonaldetails',
            old_name='id',
            new_name='pdId',
        ),
        migrations.RenameField(
            model_name='empsocialsecuritydetails',
            old_name='id',
            new_name='ssdId',
        ),
        migrations.RenameField(
            model_name='empworkdetails',
            old_name='id',
            new_name='wdId',
        ),
    ]
