# Generated by Django 5.0.6 on 2024-09-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_rename_id_empinsurancedetails_isdid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpInsuranceDetails',
        ),
        migrations.DeleteModel(
            name='EmpPersonalDetails',
        ),
        migrations.DeleteModel(
            name='EmpSocialSecurityDetails',
        ),
        migrations.DeleteModel(
            name='EmpWorkDetails',
        ),
    ]
