# Generated by Django 5.0.6 on 2024-09-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0007_delete_empinsurancedetails_delete_emppersonaldetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpWorkDetails',
            fields=[
                ('wdId', models.AutoField(primary_key=True, serialize=False)),
                ('empId', models.CharField(max_length=100)),
                ('employmentStatus', models.CharField(max_length=100)),
                ('companyEmailId', models.EmailField(max_length=254)),
                ('dateOfJoining', models.DateField()),
                ('dateOfRelieving', models.DateField(blank=True, null=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('roleType', models.CharField(max_length=100)),
                ('currentRole', models.CharField(max_length=100)),
                ('reportingManager', models.CharField(max_length=100)),
                ('reasonForLeaving', models.TextField(blank=True, null=True)),
                ('monthYearOfTermination', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExpInThisCompany', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExperience', models.CharField(blank=True, max_length=100, null=True)),
                ('totalExpBeforeJoining', models.CharField(blank=True, max_length=100, null=True)),
                ('previousDateOfJoining', models.DateField(blank=True, null=True)),
                ('previousEmployer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpSocialSecurityDetails',
            fields=[
                ('ssdId', models.AutoField(primary_key=True, serialize=False)),
                ('panNum', models.CharField(max_length=20)),
                ('uanNum', models.CharField(max_length=20)),
                ('aadharNum', models.CharField(max_length=20)),
                ('bankName', models.CharField(max_length=100)),
                ('ifscCode', models.CharField(max_length=20)),
                ('bankAccountNumber', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpPersonalDetails',
            fields=[
                ('pdId', models.AutoField(primary_key=True, serialize=False)),
                ('personalEmailId', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('educationalQualification', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('marriageDate', models.DateField(blank=True, null=True)),
                ('currentAddress', models.TextField()),
                ('permanentAddress', models.TextField()),
                ('generalContact', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('relationshipName', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('shirtSize', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmpInsuranceDetails',
            fields=[
                ('isdId', models.AutoField(primary_key=True, serialize=False)),
                ('fathersName', models.CharField(blank=True, max_length=100, null=True)),
                ('fathersDOB', models.DateField(blank=True, null=True)),
                ('mothersName', models.CharField(blank=True, max_length=100, null=True)),
                ('mothersDOB', models.DateField(blank=True, null=True)),
                ('spouseName', models.CharField(blank=True, max_length=100, null=True)),
                ('spouseDOB', models.DateField(blank=True, null=True)),
                ('child1', models.CharField(blank=True, max_length=100, null=True)),
                ('child1DOB', models.DateField(blank=True, null=True)),
                ('child2', models.CharField(blank=True, max_length=100, null=True)),
                ('child2DOB', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
    ]
