# Generated by Django 5.0.6 on 2024-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkdetails',
            name='empId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
