# Generated by Django 5.0.6 on 2024-09-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_empworkdetails_empid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empinsurancedetails',
            old_name='employee',
            new_name='wdId',
        ),
        migrations.RenameField(
            model_name='emppersonaldetails',
            old_name='employee',
            new_name='wdId',
        ),
        migrations.RenameField(
            model_name='empsocialsecuritydetails',
            old_name='employee',
            new_name='wdId',
        ),
    ]
