# Generated by Django 5.0.6 on 2024-10-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companydetails_user'),
        ('employee', '0010_rename_employee_empinsurancedetails_wdid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empworkdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.companydetails'),
        ),
        migrations.AlterField(
            model_name='empworkdetails',
            name='dateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmpSalaryDetails',
            fields=[
                ('sdId', models.AutoField(primary_key=True, serialize=False)),
                ('CTCpayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BasicpayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('HRApayAMT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AdvancesAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('VariableAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('QAllowanceAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('QBonusAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ABonusAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SAllowancesAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PTAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PFAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ESIAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DLoansAMT', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
    ]
