# Generated by Django 5.0.6 on 2024-10-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_employee_empinsurancedetails_wdid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSalaryDetails',
            fields=[
                ('sdId', models.AutoField(primary_key=True, serialize=False)),
                ('CTCpayAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('BasicpayAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('HRApayAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('AdvancesAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('VariableAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('QAllowanceAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('QBonusAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ABonusAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('SAllowancesAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('PTAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('PFAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ESIAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('DLoansAMT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('WdId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.empworkdetails')),
            ],
        ),
    ]
