# Generated by Django 5.0.6 on 2024-10-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companydetails_user'),
        ('employee', '0011_empsalarydetails'),
        ('payrole', '0008_remove_employeecompensation_gratuity'),
    ]

    operations = [
        migrations.AddField(
            model_name='empworkdetails',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.companydetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empworkdetails',
            name='compensation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payrole.employeecompensation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='ABonusAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='AdvancesAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='BasicpayAMT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='CTCpayAMT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='DLoansAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='ESIAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='HRApayAMT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='PFAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='PTAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='QAllowanceAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='QBonusAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='SAllowancesAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='VariableAMT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
