# Generated by Django 5.0.6 on 2024-10-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_empsalarydetails_vpfamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='empsalarydetails',
            name='DApayAMT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empsalarydetails',
            name='pf_type',
            field=models.CharField(blank=True, choices=[('!=15k', 'No Limit for PF Deduction'), ('15k', 'Wage limit 15k')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empsalarydetails',
            name='reimbursements',
            field=models.JSONField(default=dict),
        ),
    ]
