# Generated by Django 5.0.6 on 2024-10-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_empworkdetails_company_empworkdetails_compensation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empworkdetails',
            name='company',
        ),
        migrations.RemoveField(
            model_name='empworkdetails',
            name='compensation',
        ),
    ]
