# Generated by Django 5.0.6 on 2024-10-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_empworkdetails_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsalarydetails',
            name='BasicpayAMT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='CTCpayAMT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empsalarydetails',
            name='HRApayAMT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
