# Generated by Django 5.0.6 on 2024-10-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_empsalarydetails_basicpayamt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsalarydetails',
            old_name='WdId',
            new_name='wdId',
        ),
    ]
