# Generated by Django 5.0.6 on 2024-10-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_emppersonaldetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonaldetails',
            name='personalEmailId',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empworkdetails',
            name='companyEmailId',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
