# Generated by Django 5.0.6 on 2024-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_emppersonaldetails_personalemailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonaldetails',
            name='educationalQualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
