# Generated by Django 5.0.6 on 2024-11-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_empsocialsecuritydetails_aadharnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empworkdetails',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empworkdetails',
            name='roleType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
