# Generated by Django 5.0.6 on 2024-11-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_empworkdetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonaldetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
