# Generated by Django 5.0.6 on 2024-09-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeCompensation',
        ),
    ]
