# Generated by Django 5.0.6 on 2024-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payrole', '0002_delete_employeecompensation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('ecId', models.AutoField(primary_key=True, serialize=False)),
                ('basic_percentage', models.FloatField()),
                ('hra_percentage', models.FloatField()),
                ('advances', models.BooleanField(default=False)),
                ('variable_pay', models.BooleanField(default=False)),
                ('deductions', models.BooleanField(default=False)),
                ('gratuity', models.BooleanField(default=False)),
                ('quarterly_allowance', models.BooleanField(default=False)),
                ('quarterly_bonus', models.BooleanField(default=False)),
                ('annual_bonus', models.BooleanField(default=False)),
                ('special_allowances', models.BooleanField(default=False)),
                ('professional_tax', models.BooleanField(default=False)),
                ('esi', models.BooleanField(default=False)),
                ('esi_percentage', models.FloatField(blank=True, choices=[(0.75, '0.75% of monthly pay'), (3.25, '3.25% of monthly pay')], null=True)),
                ('pf', models.BooleanField(default=False)),
                ('pf_type', models.CharField(blank=True, choices=[('>15k', 'Greater than 15k'), ('<=15k', 'Less than or equal to 15k'), ('vpf', 'Voluntary Provident Fund')], max_length=10, null=True)),
            ],
        ),
    ]
