# Generated by Django 5.0.6 on 2024-10-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='voluntary_pf',
            field=models.CharField(blank=True, choices=[('No', 'VPF not applicable'), ('Yes', 'VPF applicable')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='pf_type',
            field=models.CharField(blank=True, choices=[('>15k', 'Greater than 15k'), ('<=15k', 'Less than or equal to 15k'), ('Both', 'Both')], max_length=10, null=True),
        ),
    ]
