# Generated by Django 5.0.6 on 2024-10-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0006_employeecompensation_voluntary_pf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompensation',
            name='esi_percentage',
        ),
    ]
