# Generated by Django 5.0.6 on 2024-10-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0007_remove_employeecompensation_esi_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompensation',
            name='gratuity',
        ),
    ]
