# Generated by Django 5.0.6 on 2024-10-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0010_employeecompensation_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee_compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='payrole.employeecompensation')),
            ],
        ),
    ]
