# Generated by Django 5.0.6 on 2024-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0011_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='is_payroll_generated',
            field=models.BooleanField(default=False),
        ),
    ]
