# Generated by Django 5.0.6 on 2024-10-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0012_employeecompensation_is_payroll_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='da_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
