# Generated by Django 5.0.6 on 2024-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0013_employeecompensation_da_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='reimbursements',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
