# Generated by Django 5.0.6 on 2024-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0014_employeecompensation_reimbursements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='pf_type',
            field=models.CharField(blank=True, choices=[('>15k', 'Greater than 15k'), ('<=15k', 'Less than or equal to 15k'), ('Both2', 'Both1')], max_length=10, null=True),
        ),
    ]
