# Generated by Django 5.0.6 on 2024-10-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0019_alter_employeecompensation_pf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='pf_type',
            field=models.CharField(blank=True, choices=[('!=15k', 'No Limit for PF Deduction'), ('15k', 'Wage limit 15k'), ('Both', 'Both Options')], max_length=10, null=True),
        ),
    ]
