# Generated by Django 5.0.6 on 2024-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0020_alter_employeecompensation_pf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='voluntary_pf',
            field=models.BooleanField(default=False),
        ),
    ]
