# Generated by Django 5.0.6 on 2024-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0021_alter_employeecompensation_voluntary_pf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='voluntary_pf',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
