# Generated by Django 5.0.6 on 2024-10-22 11:03

from django.db import migrations

def fix_voluntary_pf_values(apps, schema_editor):
    Employee = apps.get_model('payrole', 'EmployeeCompensation')  # Update with your actual model name
    Employee.objects.filter(voluntary_pf="").update(voluntary_pf=False)  # Set to False or True as needed
    Employee.objects.filter(voluntary_pf__isnull=True).update(voluntary_pf=False)

class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0022_alter_employeecompensation_voluntary_pf'),  # Update as needed
    ]

    operations = [
        migrations.RunPython(fix_voluntary_pf_values),
    ]
