# Generated by Django 5.0.6 on 2024-10-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0026_merge_20241022_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='da_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
