# Generated by Django 5.0.6 on 2024-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrole', '0027_employeecompensation_da_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensation',
            name='hra_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
